name: Run tests

on:
  #    push:
    pull_request:
      #  schedule:
      #  - cron: '0 0 * * *'

jobs:
    tests:
        strategy:
            matrix:
                os: [macOS, Ubuntu, Windows]
                php: [7.2, 7.3, 7.4]
                dependency: [prefer-lowest, prefer-stable]

                include:
                  - os: macOS
                    experimental: false
                    os-version: macos-latest

                  - os: Ubuntu
                    experimental: true
                    os-version: ubuntu-latest

                  - os: Windows
                    experimental: true
                    os-version: windows-latest

        name: ${{ matrix.os }} - PHP ${{ matrix.php }} --${{ matrix.dependency }}

        continue-on-error: ${{ matrix.experimental }}

        runs-on: ${{ matrix.os-version }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            # - name: Cache dependencies
            #   uses: actions/cache@v1
            #   with:
            #       path: ~/.composer/cache/files
            #       key: dependencies-os-${{ matrix.os }}-php-${{ matrix.php }}-laravel-${{ matrix.laravel-version }}-composer-${{ hashFiles('**/composer.lock') }}
            #       restore-keys: dependencies-os-${{ matrix.os }}-php-${{ matrix.php }}-laravel-${{ matrix.laravel-version }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Install dependencies
              run: composer update --${{ matrix.dependency }} --prefer-dist --no-interaction --no-suggest

            - name: Run tests
              run: vendor/bin/phpunit

            - name: Send Slack notification
              uses: 8398a7/action-slack@v2
              if: failure()
              with:
                  status: ${{ job.status }}
                  author_name: ${{ github.actor }}
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
